### PR TITLE
Added demo track to README

### PR DESCRIPTION
**Pull request by rileyhutton**
Hey, I absolutely love Audible Planets! I've been experimenting with it for a few days.

I noticed this plugin had no audio demos, so I created a demo track (all sounds generated by AP, except drums and FX). I thought It'd be a good sample of _some_ of its capabilities.

Being a new plugin, I understand if you'd like something else long-term, but hopefully this will suffice for now!

Thanks :)

### CODE REVIEW

**Comment by gregrecco67** [comment]
Hello! Well, that is incredibly generous of you, thanks! In case I want to add some other demos later, I'd like to add your name to it, something like: "Listen to a demo track by Riley Hutton here..." etc. Is that acceptable to you? I'm not sure what the etiquette here is, so I'll let you make that change to your fork if you agree. Or if you have another idea or want to be credited differently, let me know.

**Comment by rileyhutton** [comment]
Thank you! That's absolutely fine - I'll edit my fork to be a bullet pointed list. Of course there'll only be one entry now, but It could encourage others to create similar tracks

**Comment by rileyhutton** [comment]
Updated! Let me know if you need anything else.

**Comment by gregrecco67** [comment]
Thanks! This should do it.

**Pull request merged**
